Document: drnoksnes
Title: Debian drnoksnes Manual
Author: <insert document author here>
Abstract: This manual describes what drnoksnes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/drnoksnes/drnoksnes.sgml.gz

Format: postscript
Files: /usr/share/doc/drnoksnes/drnoksnes.ps.gz

Format: text
Files: /usr/share/doc/drnoksnes/drnoksnes.text.gz

Format: HTML
Index: /usr/share/doc/drnoksnes/html/index.html
Files: /usr/share/doc/drnoksnes/html/*.html

  
